name: Publish npm Packages

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: npm-publish-${{ github.event.inputs.ref || github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          show-progress: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false # never use cache for publishing

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm format:check

      - name: Build
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Publint
        run: pnpm exec publint

      - name: Publish package
        run: pnpm publish --provenance --no-git-checks
